# Generated by Django 5.1.7 on 2025-03-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('event_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventbooking')),
                ('room_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
