# Generated by Django 5.1.7 on 2025-05-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
