# Generated by Django 5.2.2 on 2025-06-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '__first__'),
        ('website', '0002_review_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='event_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventbooking'),
        ),
    ]
