# Generated by Django 5.1.7 on 2025-03-23 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomimage_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_images', to='rooms.roomtype'),
            preserve_default=False,
        ),
    ]
